### ISSUE TITLE
Serv .JS and CSS files 

### ISSUE THREAD

**Issue by NuclearBanane** [SuperOxigen/MakerSpaceWilkins#2]
Making the page Stylish
=====================

## Task
* Serv up a page and make sure JS and CSS files are served as well
* If required : Make Nginx guide to deploying Wilkins

**Comment by verandaguy** [comment]
As long as we set up a `StaticFIleHandler`, serving up JS and CSS (and any other fetch-able files like that) won't be a problem. See [this SO question](https://stackoverflow.com/questions/10165665/using-tornado-how-do-i-serve-static-files-and-serve-a-favicon-ico-from-a-differ).

**Comment by NuclearBanane** [comment]
The Tornado Server for the MakerSpace Project now servs CSS and JS with the HTML for greater capabilities.
